### ISSUE TITLE
UKIRT SDF files

### ISSUE THREAD

**Issue by ngc1535git** [msgordon/starlink-sdf#2]
Hi,

I am in some (desperate of course) need to manipulate UKIRT generated (astronomical) starlink SDF files. I did install your code and try to open one of them - but received an index error. Is there possibly a simple something that might allow me to take advantage of your code. I would like to write a small python script to examine the metadata (header info) of many hundreds of files and organize them- without having to install and learn the Starlink software (or its wrapper). 

An example file can be found here:
https://emailarizona-my.sharepoint.com/:u:/g/personal/ngc1535_arizona_edu/EdzLcxTWBexEnhT1BTZoS0oB2JkZ4KglKe4oTwwd-t0OHw?e=I2Gu1P

Please help!
Thanks,
Adam

**Comment by msgordon** [comment]
Hi Adam,

   Thanks for dropping me a line on this!  Always glad to hear this little module is getting some usage.  I have provisionally patched the code to successfully ingest UKIRT/WFCAM .sdf files.  I will confess that I am not the most familiar with the WFCAM header keywords, but the conversion should capture the data array, headers, and WCS information.

   The .sdf files are formatted differently than the JCMT baseline I used to build this library, so some starlink functionality will not work.  However, I have tested your input file and a few other samples from UKIRT with the command line `sdf2fits` interface, as well as the `sdf.open('some_sdf_file.sdf')` interface, and the conversion should now work.  Note that for some WFCAM files, the primary fits extension is called `I1`.

   Update your copy by issuing:
`pip install git+https://github.com/msgordon/starlink-sdf.git`

  Feel free to respond here with any further issues.

**Comment by ngc1535git** [comment]
Absolutely AMAZING. This will help me out so much. I will try to update and run the new code. We have acquired quite a bit of IR spectra and the files need to be organized in order to be processed- this will be so helpful. 

I can't thank you enough... let me give it a try. The file I gave you was a WFCAM image- I assume the other data from the Michelle spectrograph and UIST spectrometer will have the same format (it really should). 

I will write back with a success story.
-adam

**Comment by ngc1535git** [comment]
Thank you again. I was able to mostly do what I needed. You can see the attached txt file (I did not want to attach an excel file). But some directories of data have something in the header that is tripping up things. I suspect you probably know what this is. At the moment I a just trying to read in the meta data- but I think this WCS checking is probably a side issue.  So for many files I have no issue...then for some files I do. I do not know..but likely the operator used a different file saving method/format? See:

WARNING: FITSFixedWarning: 'celfix' made the change 'Linear transformation matrix is singular'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "/home/ngc1535/.local/lib/python3.8/site-packages/starlink/sdf/sdf.py", line 189, in extract_wcs
    fs = c.read()
Ast.BADIN: astRead(Channel): Cannot interpret the input data: "Identification:".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "UKIRT_scan_SDF_Headers.py", line 90, in <module>
    main()
  File "UKIRT_scan_SDF_Headers.py", line 47, in main
    hdul = sdf.open(FitsList[i])
  File "/home/ngc1535/.local/lib/python3.8/site-packages/starlink/sdf/sdf.py", line 408, in sdfopen
    hdlist = [getdata(hd, ext='ukirt', as_hdu=True)]
  File "/home/ngc1535/.local/lib/python3.8/site-packages/starlink/sdf/sdf.py", line 384, in getdata
    data = extract_data(filename, **opts)
  File "/home/ngc1535/.local/lib/python3.8/site-packages/starlink/sdf/sdf.py", line 338, in extract_data
    header = extract_header(data, header_path=header_path,
  File "/home/ngc1535/.local/lib/python3.8/site-packages/starlink/sdf/sdf.py", line 260, in extract_header
    wcs = extract_wcs(data, header_path)
  File "/home/ngc1535/.local/lib/python3.8/site-packages/starlink/sdf/sdf.py", line 200, in extract_wcs
    wcs = WCS(h)
  File "/home/ngc1535/.local/lib/python3.8/site-packages/astropy/wcs/wcs.py", line 514, in __init__
    self.wcs.set()
astropy.wcs._wcs.SingularMatrixError: ERROR 3 in wcsset() at line 2507 of file cextern/wcslib/C/wcs.c:
Linear transformation matrix is singular.
ERROR 3 in linset() at line 677 of file cextern/wcslib/C/lin.c:
PCi_ja matrix is singular.

This is the file: https://emailarizona-my.sharepoint.com/:u:/g/personal/ngc1535_arizona_edu/Ebu_gbR4x1dCpmtdFZOUhCEBzRL7cGvr91RlPTBmn5JpuA?e=U3zoud

Again... many files work- but unfortunately there is something that is not consistent. I see the area of the code you added stuff in sdf.py... but I do not know what to change. 

See the attached for my successfully run of one directory of files.
[sdf_metadata.txt](https://github.com/msgordon/starlink-sdf/files/9172925/sdf_metadata.txt)

**Comment by msgordon** [comment]
Hmm, I was unable to recreate that error message on the file you posted.  Still, I did add some error checking on the WCS processing, so issue another `pip install` and give it a try.  If you are still having issues, let me know and I will take another look.

**Comment by ngc1535git** [comment]
There is a chance I did not give you the correct file and I was off by one. However, I just tried the new version and indeed it did not complain this time! 

Again...thank you so much. I will continue to parse the data this evening and write again if there is an issue. I am suspecting not... but who knows. 

Although I do not need the capability at the moment, am I correct that I could ingest SDF with your code and output FITs? (that would be helpful for other reasons)

-adam

**Comment by msgordon** [comment]
Glad to hear it.  And yes, it was designed as a converter.  On install, a command line program `sdf2fits` is added to your PATH.  Run it as `sdf2fits -h` for instructions.  Or, you could do:

```
from starlink import sdf
hdul = sdf.open('some_file.sdf')
hdul.writeto('some_file.fits')
```

`sdf.open()` returns an [HDUList](https://docs.astropy.org/en/stable/io/fits/api/hdulists.html) object, so you can interact with it using that interface.

**Comment by ngc1535git** [comment]
Thanks again. I suspect I will be utilizing the conversion later (so you *might* hear from me again). But for the moment, I did create some nice stuff from the header information. Your code is likely the only thing that exists to do this (AFAIK). I mentioned it to one of the UKIRT staff as well and he was very interested. 

-adam
